name: Landscape
favicon: null
layout_spectrum: 0.25101
typography_spectrum: 0.2363155207131058
title: Vision By Choice
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212540'
    - '#4d5181'
    - '#986e7a'
    - '#ec988d'
    - '#f7cfb6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.2995183614548296
purpose: []
