name: visionbychoice
favicon: null
layout_spectrum: 0.73886
typography_spectrum: 0.2363155207131058
title: Vision By Choice
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a3134'
    - '#464b50'
    - '#898a8f'
    - '#afaeb2'
    - '#131b22'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
